#!/usr/bin/env bash
set -euo pipefail

export EXPERIMENT_NAME="${EXPERIMENT_NAME:-hotpotqa-search-r1-er-entropy-calibration}"
export OPD_ENTROPY_CALIBRATION_ENABLE=true
export OPD_ENTROPY_CALIBRATION_FRACTION="${OPD_ENTROPY_CALIBRATION_FRACTION:-0.05}"
export OPD_ENTROPY_CALIBRATION_SPLIT_SEED="${OPD_ENTROPY_CALIBRATION_SPLIT_SEED:-42}"
export OPD_ENTROPY_CALIBRATION_DECODE_SEED="${OPD_ENTROPY_CALIBRATION_DECODE_SEED:-42}"
export OPD_ENTROPY_CALIBRATION_DATA_SOURCE="${OPD_ENTROPY_CALIBRATION_DATA_SOURCE:-hotpotqa}"
export OPD_ENTROPY_CALIBRATION_OUTPUT="${OPD_ENTROPY_CALIBRATION_OUTPUT:-refine-logs/ER_ENTROPY_CALIBRATION.json}"
export OPD_ROLLOUT_SEED="$OPD_ENTROPY_CALIBRATION_DECODE_SEED"
export OPD_DIAGNOSTICS_ENABLE=false
export TOTAL_TRAINING_STEPS=1

exec bash "$(dirname "$0")/train_er_opd.sh" "$@"
