#!/usr/bin/env bash
set -euo pipefail

# Search-R1 baseline adaptation of YoungZ365/SOD commit 110c4b8.  Defaults
# intentionally match train_er_opd.sh's 1B two-GPU run wherever SOD does not
# define the experimental variable.

export NO_PROXY="${NO_PROXY:+${NO_PROXY},}127.0.0.1,localhost"
export no_proxy="${no_proxy:+${no_proxy},}127.0.0.1,localhost"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-2,3}"
export VLLM_ATTENTION_BACKEND="${VLLM_ATTENTION_BACKEND:-XFORMERS}"

DATA_DIR="${DATA_DIR:-data/nq_hotpotqa_train_30k_no_cold_start}"
VAL_FILE="${VAL_FILE:-$DATA_DIR/validation_diagnostic_512.parquet}"
TRAIN_DATA_SOURCE="${TRAIN_DATA_SOURCE:-hotpotqa}"
VAL_DATA_SOURCE="${VAL_DATA_SOURCE:-null}"
STUDENT_MODEL="${STUDENT_MODEL:-data/student/1B}"
TEACHER_MODEL="${TEACHER_MODEL:-/data/home/wencanning/models/SearchR1-nq_hotpotqa_train-qwen2.5-7b-it-em-grpo-v0.3}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-sod-grpo-1B}"
WAND_PROJECT="${WAND_PROJECT:-Search-R1-OPD2}"
N_GPUS="${N_GPUS:-$(awk -F, '{print NF}' <<< "$CUDA_VISIBLE_DEVICES")}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-201}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-128}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-256}"
SOD_PPO_MINI_BATCH_SIZE="${SOD_PPO_MINI_BATCH_SIZE:-128}"
SOD_PPO_MICRO_BATCH_SIZE="${SOD_PPO_MICRO_BATCH_SIZE:-8}"
SOD_ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE="${SOD_ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE:-32}"
SOD_REF_LOG_PROB_MICRO_BATCH_SIZE="${SOD_REF_LOG_PROB_MICRO_BATCH_SIZE:-8}"
SOD_LAMBDA_DISTILL="${SOD_LAMBDA_DISTILL:-1.0}"
SOD_GRPO_REWARD_COEF="${SOD_GRPO_REWARD_COEF:-1.0}"
SOD_N_AGENT="${SOD_N_AGENT:-8}"
SOD_EPSILON="${SOD_EPSILON:-1e-6}"
SOD_DELTA="${SOD_DELTA:-0.2}"

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    data.train_files="$DATA_DIR/train.parquet" \
    data.val_files="$VAL_FILE" \
    data.train_data_source="$TRAIN_DATA_SOURCE" \
    data.val_data_source="$VAL_DATA_SOURCE" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.val_batch_size="$VAL_BATCH_SIZE" \
    data.max_prompt_length=5120 \
    data.max_response_length=512 \
    data.max_start_length=2048 \
    data.max_obs_length=512 \
    algorithm.adv_estimator=opd \
    algorithm.opd.advantage_mode=token \
    algorithm.opd.normalize=false \
    algorithm.opd.clip_value=null \
    algorithm.opd.distillation_coef="$SOD_LAMBDA_DISTILL" \
    algorithm.opd.mask_protocol_tags=false \
    algorithm.opd.lambda_distill="$SOD_LAMBDA_DISTILL" \
    algorithm.opd.teacher_target=observed \
    algorithm.opd.grpo_reward_coef="$SOD_GRPO_REWARD_COEF" \
    algorithm.opd.use_gated_distillation=false \
    algorithm.opd.rce.enable=false \
    algorithm.opd.sod.enable=true \
    algorithm.opd.sod.epsilon="$SOD_EPSILON" \
    algorithm.opd.sod.delta="$SOD_DELTA" \
    algorithm.opd.diagnostics.enable=false \
    algorithm.no_think_rl=false \
    actor_rollout_ref.model.path="$STUDENT_MODEL" \
    actor_rollout_ref.ref.model_path="$TEACHER_MODEL" \
    actor_rollout_ref.ref.attn_implementation=sdpa \
    actor_rollout_ref.ref.target_forward_dtype=float16 \
    actor_rollout_ref.ref.allow_approximate_target_precision=true \
    actor_rollout_ref.ref.fsdp_config.model_dtype=float16 \
    actor_rollout_ref.ref.fsdp_config.mixed_precision.param_dtype=float16 \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size="$SOD_PPO_MINI_BATCH_SIZE" \
    actor_rollout_ref.actor.ppo_micro_batch_size="$SOD_PPO_MICRO_BATCH_SIZE" \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_c=3.0 \
    actor_rollout_ref.actor.use_kl_loss=false \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.state_masking=true \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
    actor_rollout_ref.rollout.log_prob_micro_batch_size="$SOD_ROLLOUT_LOG_PROB_MICRO_BATCH_SIZE" \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.restrict_to_tokenizer_vocab=true \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.n_agent="$SOD_N_AGENT" \
    actor_rollout_ref.ref.log_prob_micro_batch_size="$SOD_REF_LOG_PROB_MICRO_BATCH_SIZE" \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=false \
    actor_rollout_ref.ref.fsdp_config.param_offload=false \
    trainer.logger=['console','wandb'] \
    +trainer.val_before_train=false \
    +trainer.val_only=false \
    trainer.n_gpus_per_node="$N_GPUS" \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.project_name="$WAND_PROJECT" \
    trainer.experiment_name="$EXPERIMENT_NAME" \
    trainer.total_epochs=15 \
    trainer.total_training_steps="$TOTAL_TRAINING_STEPS" \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir="verl_checkpoints/$EXPERIMENT_NAME" \
    max_turns=4 \
    retriever.url="http://127.0.0.1:8000/retrieve" \
    retriever.topk=3 "$@"
