#!/usr/bin/env bash
set -euo pipefail

export EXPERIMENT_NAME="${EXPERIMENT_NAME:-nq-search-r1-plain-opd}"
export OPD_GRPO_REWARD_COEF="${OPD_GRPO_REWARD_COEF:-0.0}"
export OPD_USE_GATED_DISTILLATION="${OPD_USE_GATED_DISTILLATION:-false}"
export OPD_N_AGENT="${OPD_N_AGENT:-8}"
export OPD_DIAGNOSTICS_ENABLE="${OPD_DIAGNOSTICS_ENABLE:-true}"
export OPD_DIAGNOSTICS_OUTPUT_DIR="${OPD_DIAGNOSTICS_OUTPUT_DIR:-verl_checkpoints/${EXPERIMENT_NAME}/opd_diagnostics}"
export OPD_DIAGNOSTICS_EVERY_N_STEPS="${OPD_DIAGNOSTICS_EVERY_N_STEPS:-1}"
export OPD_DIAGNOSTICS_MAX_SEQUENCES="${OPD_DIAGNOSTICS_MAX_SEQUENCES:-512}"
export OPD_DIAGNOSTICS_SAMPLE_STRATEGY="${OPD_DIAGNOSTICS_SAMPLE_STRATEGY:-random}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-50}"
exec bash "$(dirname "$0")/train_opd.sh"
