#!/usr/bin/env bash
set -euo pipefail

export NO_PROXY="${NO_PROXY:+${NO_PROXY},}127.0.0.1,localhost"
export no_proxy="${no_proxy:+${no_proxy},}127.0.0.1,localhost"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4,5}"
export VLLM_ATTENTION_BACKEND="${VLLM_ATTENTION_BACKEND:-XFORMERS}"

DATA_DIR="${DATA_DIR:-data/nq_hotpotqa_train_30k_no_cold_start}"
TRAIN_FILE="${TRAIN_FILE:-$DATA_DIR/train.parquet}"
VAL_FILE="${VAL_FILE:-$DATA_DIR/validation_diagnostic_512.parquet}"
STUDENT_MODEL="${STUDENT_MODEL:-data/student}"
TEACHER_MODEL="${TEACHER_MODEL:-/data/home/wencanning/models/SearchR1-nq_hotpotqa_train-qwen2.5-7b-it-em-grpo-v0.3}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-nq-search-r1-rcod}"
WAND_PROJECT="${WAND_PROJECT:-Search-R1-OPD}"
N_GPUS="${N_GPUS:-$(awk -F, '{print NF}' <<< "$CUDA_VISIBLE_DEVICES")}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"

OPD_DISTILLATION_COEF="${OPD_DISTILLATION_COEF:-1.0}"
OPD_GRPO_REWARD_COEF="${OPD_GRPO_REWARD_COEF:-1.0}"
OPD_USE_GATED_DISTILLATION="${OPD_USE_GATED_DISTILLATION:-true}"
OPD_GATE_GAMMA="${OPD_GATE_GAMMA:-1.0}"
OPD_GATE_BETA_MIN="${OPD_GATE_BETA_MIN:-0.0}"
OPD_GATE_BETA_MAX="${OPD_GATE_BETA_MAX:-0.05}"
OPD_N_AGENT="${OPD_N_AGENT:-8}"

OPD_RCE_ENABLE="${OPD_RCE_ENABLE:-true}"
OPD_RCE_ENTROPY_NORMALIZATION="${OPD_RCE_ENTROPY_NORMALIZATION:-percentile_rank}"
OPD_RCE_W_MIN="${OPD_RCE_W_MIN:-0.1}"
OPD_RCE_W_MAX="${OPD_RCE_W_MAX:-1.0}"
OPD_RCE_ALPHA="${OPD_RCE_ALPHA:-4.0}"
OPD_RCE_TAU="${OPD_RCE_TAU:-0.0}"
OPD_RCE_DEFAULT_RETRIEVAL_HIT="${OPD_RCE_DEFAULT_RETRIEVAL_HIT:-0.5}"

OPD_DIAGNOSTICS_ENABLE="${OPD_DIAGNOSTICS_ENABLE:-false}"
OPD_DIAGNOSTICS_OUTPUT_DIR="${OPD_DIAGNOSTICS_OUTPUT_DIR:-null}"
OPD_DIAGNOSTICS_EVERY_N_STEPS="${OPD_DIAGNOSTICS_EVERY_N_STEPS:-1}"
OPD_DIAGNOSTICS_MAX_SEQUENCES="${OPD_DIAGNOSTICS_MAX_SEQUENCES:-64}"
OPD_DIAGNOSTICS_SAMPLE_STRATEGY="${OPD_DIAGNOSTICS_SAMPLE_STRATEGY:-random}"
OPD_DIAGNOSTICS_COMPRESS="${OPD_DIAGNOSTICS_COMPRESS:-false}"

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    data.train_files="$TRAIN_FILE" \
    data.val_files="$VAL_FILE" \
    data.train_batch_size=128 \
    data.val_batch_size=256 \
    data.max_prompt_length=5120 \
    data.max_response_length=512 \
    data.max_start_length=2048 \
    data.max_obs_length=512 \
    data.shuffle_train_dataloader=True \
    algorithm.adv_estimator=opd \
    algorithm.opd.advantage_mode=token \
    algorithm.opd.normalize=false \
    algorithm.opd.clip_value=null \
    algorithm.opd.distillation_coef="$OPD_DISTILLATION_COEF" \
    algorithm.opd.grpo_reward_coef="$OPD_GRPO_REWARD_COEF" \
    algorithm.opd.use_gated_distillation="$OPD_USE_GATED_DISTILLATION" \
    algorithm.opd.gamma="$OPD_GATE_GAMMA" \
    algorithm.opd.beta_min="$OPD_GATE_BETA_MIN" \
    algorithm.opd.beta_max="$OPD_GATE_BETA_MAX" \
    algorithm.opd.rce.enable="$OPD_RCE_ENABLE" \
    algorithm.opd.rce.entropy_normalization="$OPD_RCE_ENTROPY_NORMALIZATION" \
    algorithm.opd.rce.w_min="$OPD_RCE_W_MIN" \
    algorithm.opd.rce.w_max="$OPD_RCE_W_MAX" \
    algorithm.opd.rce.alpha="$OPD_RCE_ALPHA" \
    algorithm.opd.rce.tau="$OPD_RCE_TAU" \
    algorithm.opd.rce.default_retrieval_hit="$OPD_RCE_DEFAULT_RETRIEVAL_HIT" \
    algorithm.opd.diagnostics.enable="$OPD_DIAGNOSTICS_ENABLE" \
    algorithm.opd.diagnostics.output_dir="$OPD_DIAGNOSTICS_OUTPUT_DIR" \
    algorithm.opd.diagnostics.every_n_steps="$OPD_DIAGNOSTICS_EVERY_N_STEPS" \
    algorithm.opd.diagnostics.max_sequences_per_step="$OPD_DIAGNOSTICS_MAX_SEQUENCES" \
    algorithm.opd.diagnostics.sample_strategy="$OPD_DIAGNOSTICS_SAMPLE_STRATEGY" \
    algorithm.opd.diagnostics.compress="$OPD_DIAGNOSTICS_COMPRESS" \
    algorithm.no_think_rl=false \
    actor_rollout_ref.model.path="$STUDENT_MODEL" \
    actor_rollout_ref.ref.model_path="$TEACHER_MODEL" \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size=8 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_c=3.0 \
    actor_rollout_ref.actor.use_kl_loss=false \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.state_masking=true \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n_agent="$OPD_N_AGENT" \
    actor_rollout_ref.rollout.temperature=1 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=false \
    trainer.logger=['console','wandb'] \
    +trainer.val_before_train=false \
    +trainer.val_only=false \
    trainer.n_gpus_per_node="$N_GPUS" \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.project_name="$WAND_PROJECT" \
    trainer.experiment_name="$EXPERIMENT_NAME" \
    trainer.total_epochs=15 \
    trainer.total_training_steps="$TOTAL_TRAINING_STEPS" \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir="verl_checkpoints/$EXPERIMENT_NAME" \
    max_turns=4 \
    retriever.url="http://127.0.0.1:8000/retrieve" \
    retriever.topk=3 \
    2>&1 | tee "$EXPERIMENT_NAME.log"
